services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: alwib
      POSTGRES_USER: alwib
      POSTGRES_PASSWORD: alwib
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U alwib -d alwib']
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://alwib:alwib@postgres:5432/alwib?schema=public
      JWT_SECRET: replace-this-with-long-random-secret
      FRONTEND_URL: http://localhost:5173
      FRONTEND_URLS: http://localhost:5173,http://localhost:5174
      FRONTEND_OAUTH_REDIRECT_URL: http://localhost:5173/auth
      CORS_ALLOW_PRIVATE_NETWORK: 'true'
      GOOGLE_CLIENT_ID: ''
      GOOGLE_CLIENT_SECRET: ''
      GOOGLE_CALLBACK_URL: http://localhost:3000/auth/google/callback
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: '587'
      SMTP_SECURE: 'false'
      SMTP_USER: tsuevjudoka@gmail.com
      SMTP_PASS: svzw yfyy qmft cqrw
      SMTP_FROM: tsuevjudoka@gmail.com
      XUI_BASE_URL: https://alwib.ru:27419/wayvpn/
      XUI_USERNAME: qari
      XUI_PASSWORD: 8447080vasman
      XUI_INBOUND_ID: '1'
      XUI_ALLOW_INSECURE_TLS: 'true'
      XUI_ONLINE_WINDOW_SECONDS: '300'
    command: sh -c "npx prisma migrate deploy && npm run start:prod"
    ports:
      - '3000:3000'

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    ports:
      - '5173:5173'

volumes:
  postgres_data:
